[project]
name = "babitag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "cloudscraper>=1.2.71",
    "selenium>=4.39.0",
    "yt-dlp>=2025.12.8",
]
